### ISSUE TITLE
Is logical replication supported?

### ISSUE THREAD

**Issue by jugaadi** [benbjohnson/postlite#10]

**Comment by benbjohnson** [comment]
@jugaadi No, Postlite simply wraps the SQLite query API with a Postgres proxy so it doesn’t adapt any additional Postgres features to SQLite.

**Comment by gedw99** [comment]
I was also hoping for this feature so we can do what fly.io does with PostgreSQL. Like have many read only and one master and redirecting the network connection based on if it’s a sql read or write . 

Sort of related to replication :)
