### ISSUE TITLE
Possible to use postlite to query osQuery endpoints?

### ISSUE THREAD

**Issue by shah** [benbjohnson/postlite#13]
This is a very slick little utility - I have a similar need ... accessing [osQuery](https://osquery.io/) endpoints. osQuery has its own, special, access points but it would much nicer to have a PostgreSQL wire compatible interface to osQuery endpoints. 

Since osQuery is built on top of SQLite, does anyone know if a PostgreSQL wire compatible interface to osQuery endpoints is possible with `postlite`?

**Comment by benbjohnson** [comment]
@shah If osquery is able to be loaded as a runtime extension (e.g. `.load`) then you might be able to use it through Postlite. However, Postlite is still very alpha so just be careful. 👍

**Comment by shah** [comment]
Thanks for the direction @benbjohnson - I do not believe osQuery can be loaded as a runtime extension but I'll dig further. Please keep working on `postlite`, it's a fantastic idea! :-)
