### ISSUE TITLE
add support for pg_range as virtual table

### ISSUE THREAD

**Issue by rogerwelin** [benbjohnson/postlite#14]
Hi and thanks for a great project. I tried using postlite/sqlite when running some integration tests locally. Sadly they fail because postlite does not support the pg_range catalog table. Would it be possible to add this feature?

**Comment by benbjohnson** [comment]
hey @rogerwelin. Yes, that can be added. I'm busy with some other projects right now but I'm open to a PR for the feature if you're up for adding it.
